#Tupla – Crie uma tupla com 6 cidades. Depois exiba:
#• A primeira cidade
#• A última cidade
#• Quantas cidades existem
#• Todas as cidades uma por linha

cidades = ("Vitória","Rio de Janeiro","São Paulo","Porto Alegre","Fortaleza","Rio Branco")
primeiro_item = {cidades[0]}
ultimo_item = {cidades[-1]}
print(f"O primeiro item é: {primeiro_item} ""\n")
print(f"O último item é: {ultimo_item}""\n")
print(f"A quantidade de cidades é de: {len(cidades)}\n")
print(f"{cidades}")